/**
 * This file was generated by Payload.
 * DO NOT MODIFY IT BY HAND.
 * Instead, regenerate it by running `payload generate:types`.
 */

export interface Config {
  collections: {
    users: User
    courses: Course
    'blog-posts': BlogPost
    banners: Banner
    testimonials: Testimonial
    enquiries: Enquiry
    media: Media
    'site-settings': SiteSetting
  }
}

export interface User {
  id: string
  name: string
  role: 'admin' | 'editor'
  email: string
  updatedAt: string
  createdAt: string
}

export interface Course {
  id: string
  name: string
  category:
    | 'nursing'
    | 'pharmacy'
    | 'btech'
    | 'diploma'
    | 'management'
    | 'education'
    | 'general-degree'
    | 'others'
  shortDescription?: string
  duration?: string
  eligibility?: any
  careerScope?: any
  admissionGuidance?: any
  featured?: boolean
  order?: number
  updatedAt: string
  createdAt: string
}

export interface BlogPost {
  id: string
  title: string
  slug: string
  excerpt: string
  content: any
  featuredImage?: string | Media
  author?: string
  tags?: {
    tag?: string
    id?: string
  }[]
  publishedAt?: string
  status: 'draft' | 'published'
  updatedAt: string
  createdAt: string
}

export interface Banner {
  id: string
  excerpt?: string
  headline: string
  subheadline?: string
  ctaText?: string
  ctaLink?: string
  secondaryCtaText?: string
  secondaryCtaLink?: string
  backgroundImage?: string | Media
  active?: boolean
  order?: number
  updatedAt: string
  createdAt: string
}

export interface Testimonial {
  id: string
  studentName: string
  course: string
  quote: string
  photo?: string | Media
  rating?: number
  featured?: boolean
  updatedAt: string
  createdAt: string
}

export interface Enquiry {
  id: string
  name: string
  phone: string
  email?: string
  course?: string
  message?: string
  source?: string
  status: 'new' | 'contacted' | 'converted' | 'closed'
  updatedAt: string
  createdAt: string
}

export interface Media {
  id: string
  alt: string
  updatedAt: string
  createdAt: string
  url?: string
  thumbnailURL?: string
  filename?: string
  mimeType?: string
  filesize?: number
  width?: number
  height?: number
}

export interface SiteSetting {
  id: string
  siteName: string
  siteTagline?: string
  siteLogo?: string | Media
  siteFavicon?: string | Media
  contactInfo?: {
    address: string
    phone: string
    alternatePhone?: string
    whatsapp: string
    whatsappMessage?: string
    email: string
    secondaryEmail?: string
  }
  socialMedia?: {
    facebook?: string
    instagram?: string
    youtube?: string
    twitter?: string
    linkedin?: string
  }
  location?: {
    googleMapsEmbedUrl: string
    latitude?: number
    longitude?: number
  }
  legalPages?: {
    privacyPolicy?: any
    termsAndConditions?: any
    disclaimer?: any
  }
  businessHours?: {
    workingDays?: string
    workingHours?: string
    closedDays?: string
  }
  seo?: {
    metaDescription?: string
    keywords?: {
      keyword?: string
      id?: string
    }[]
    googleAnalyticsId?: string
  }
  footer?: {
    copyrightText?: string
    showLegalLinks?: boolean
  }
  updatedAt: string
  createdAt: string
}
